version: '3.8'

services:

  postgres:
    image: postgres:16
    restart: always
    container_name: db_test
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pizzaria_api
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"